#!/usr/bin/python3
import os
import sys
import multiprocessing as mp
from prettytable import PrettyTable

def run():
    k=64
    row = str(sys.argv[1])
    col =str(sys.argv[2])
    os.system("java -cp bin MonteCarloMinimization " + row + " " + col+ " 200 200 22 -200 0.1")
    for i in range(20): 
        cutoff = str(k)
        os.system("java -cp bin MonteCarloMinimizationParallel " +row + " " + col+ " 200 200 22 -200 0.1 " + cutoff)
        k = k*2
        

if __name__=='__main__':
    run()
    print("q")
       
    
    

