#!/usr/bin/python3
import os
import sys

def run():
    k=2**25
    row = str(sys.argv[1])
    col =str(sys.argv[2])
    os.system("java -cp bin MonteCarloMinimization " + row + " " + col+ " 1000 200 222 -2003 0.3")
    for i in range(25): 
        cutoff = str(k)
        os.system("java -cp bin MonteCarloMinimizationParallel " +row + " " + col+ " 1000 200 222 -2003 0.3 " + cutoff)
        k = int(k/2)
        

if __name__=='__main__':
    run()
    print("q")
       
    
    

